# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('speed', models.FloatField()),
                ('stamina', models.FloatField()),
                ('skill1', models.CharField(choices=[('Tiedtogether', 'Tiedtogether'), ('Kick', 'Kick'), ('Grow', 'Grow')], default='Kick', max_length=32)),
                ('skill2', models.CharField(choices=[('Tiedtogether', 'Tiedtogether'), ('Kick', 'Kick'), ('Grow', 'Grow')], default='Tiedtogether', max_length=32)),
                ('owner', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
