# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('speed', models.FloatField()),
                ('stamina', models.FloatField()),
            ],
        ),
    ]
