# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill1',
            field=models.CharField(choices=[('Tiedtogether', 'Tiedtogether'), ('Kick', 'Kick'), ('Grow', 'Grow')], default='Kick', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='skill2',
            field=models.CharField(choices=[('Tiedtogether', 'Tiedtogether'), ('Kick', 'Kick'), ('Grow', 'Grow')], default='Tiedtogether', max_length=32),
        ),
    ]
