# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='character',
            name='stamina',
            field=models.FloatField(default=200),
        ),
    ]
